---
####################################################
#          ModuleBuilder Configuration             #
####################################################
# Path to the Module Manifest to build (where path will be resolved from)
# SourcePath: ./Sampler/Sampler.psd1
# Output Directory where ModuleBuilder will build the Module, relative to module manifest
# OutputDirectory: ../output/Sampler
CopyDirectories:
  - DSCResources
  - en-US
# SemVer: '1.2.3'
# Suffix to add to Root module PSM1 after merge (here, the Set-Alias exporting IB tasks)
# suffix: suffix.ps1
VersionedOutputDirectory: true

####################################################
#      ModuleBuilder Submodules Configuration      #
####################################################

# NestedModule:
#   HelperSubmodule: # This is the first submodule to build into the output
#     Path: ./Sampler/Modules/HelperSubmodule/HelperSubmodule.psd1
#     # $ModuleVersionFolder is trimmed (remove -.*) and OutputDirectory expanded (the only one)
#     OutputDirectory: ./output/Sampler/$ModuleVersionFolder/Modules/HelperSubmodule
#     VersionedOutputDirectory: false
#     # suffix:
#     # prefix:



####################################################
#       Sampler Pipeline Configuration             #
####################################################
# Defining 'Workflows' (suite of InvkeBuild tasks) to be run using their alias
BuildWorkflow:

  '.': # "." is the default Invoke-Build workflow. It is called when no -Tasks is specified to the build.ps1
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Pester_Tests_Stop_On_Fail
    - Pester_if_Code_Coverage_Under_Threshold

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder

  # defining test task to be run when invoking `./build.ps1 -Tasks test`
  test:
    - Pester_Tests_Stop_On_Fail
    - Pester_if_Code_Coverage_Under_Threshold

Resolve-Dependency: #Parameters for Resolve-Dependency
  #PSDependTarget: ./output/modules
  #Proxy: ''
  #ProxyCredential:
  Gallery: 'PSGallery'
  # AllowOldPowerShellGetModule: true
  #MinimumPSDependVersion = '0.3.0'
  AllowPrerelease: false
  Verbose: false

ModuleBuildTasks:
  # - ModuleName: 'alias to search'
  - Sampler: '*.ib.tasks' # this means: import (dot source) all aliases ending with .ib.tasks exported by sampler module

# Invoke-Build Header to be used to 'decorate' the terminal output of the tasks.
TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""
